CREATE OR REPLACE VIEW `bidbrain-analytics.client_mongodb.paid_media_model` AS
SELECT "TradeDesk" AS CHANNEL, DAY AS DATE, DATE_TRUNC(DAY, WEEK(MONDAY)) AS WEEK_START,
  PROGRAMME, MARKET, STRATEGY, OBJECTIVE, CAMPAIGN_NAME, AD_GROUP_NAME, PUBLISHER, CREATIVE_FORMAT,
  SUM(IMPRESSIONS) AS IMPS, SUM(CLICKS) AS CLICKS, SUM(COSTS) AS SPEND_USD,
  SUM(CONVERSIONS) AS CONVERSIONS, 0 AS LEADS
FROM `bidbrain-analytics.client_mongodb.stg_tradedesk` GROUP BY ALL
