CREATE OR REPLACE VIEW `bidbrain-analytics.client_mongodb.targets` AS
SELECT * FROM UNNEST([
  STRUCT("DNB Multi-Touch" AS PROGRAMME_LABEL,"ANZ" AS MARKET,46 AS TARGET_LEADS,43 AS DELIVERED_LEADS_SNAPSHOT),
  STRUCT("DNB Multi-Touch","INDIA",105,79),STRUCT("DNB Multi-Touch","KR-HK-TW",70,39),STRUCT("DNB Multi-Touch","ASEAN",86,73),
  STRUCT("DNB Pulse Survey","ANZ",14,18),STRUCT("DNB Pulse Survey","INDIA",27,27),STRUCT("DNB Pulse Survey","KR-HK-TW",16,9),
  STRUCT("DNB Pulse Survey","ASEAN",25,29),STRUCT("KGA IDC Report","ANZ",90,40),STRUCT("KGA IDC Report","INDIA",209,52),
  STRUCT("KGA IDC Report","KR-HK-TW",139,28),STRUCT("KGA IDC Report","ASEAN",171,54)])
