CREATE OR REPLACE VIEW `bidbrain-analytics.client_mongodb.targets_by_programme` AS
SELECT PROGRAMME_LABEL, SUM(TARGET_LEADS) AS TARGET_LEADS, SUM(DELIVERED_LEADS_SNAPSHOT) AS DELIVERED_LEADS,
  ROUND(SUM(DELIVERED_LEADS_SNAPSHOT)/NULLIF(SUM(TARGET_LEADS),0),4) AS ACHIEVEMENT_PCT
FROM `bidbrain-analytics.client_mongodb.targets` GROUP BY PROGRAMME_LABEL
