CREATE OR REPLACE VIEW `bidbrain-analytics.raw_ga4.perf_ga4` AS
SELECT
  'ga4'                                 AS platform,
  '318963196'                              AS property_id,
  'STT GDC Web All'                            AS account_name,
  'stt'                                AS client_slug,
  'unknown'                                AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_318963196` t;
