CREATE OR REPLACE VIEW `bidbrain-analytics.raw_ga4.perf_ga4` AS
SELECT
  'ga4'                                 AS platform,
  '254028250'                              AS property_id,
  'City Perfume'                       AS account_name,
  'city-perfume'                         AS client_slug,
  '100-digital'                         AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_254028250` t
UNION ALL
SELECT
  'ga4'                                 AS platform,
  '318963196'                              AS property_id,
  'STT GDC Web All'                       AS account_name,
  'stt-gdc-web-all'                         AS client_slug,
  '100-digital'                         AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_318963196` t
UNION ALL
SELECT
  'ga4'                                 AS platform,
  '413451542'                              AS property_id,
  'STT GDC Web India'                       AS account_name,
  'stt-gdc-web-india'                         AS client_slug,
  '100-digital'                         AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_413451542` t
UNION ALL
SELECT
  'ga4'                                 AS platform,
  '413487460'                              AS property_id,
  'STT GDC Web Indonesia'                       AS account_name,
  'stt-gdc-web-indonesia'                         AS client_slug,
  '100-digital'                         AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_413487460` t
UNION ALL
SELECT
  'ga4'                                 AS platform,
  '413490347'                              AS property_id,
  'STT GDC Web Singapore'                       AS account_name,
  'stt-gdc-web-singapore'                         AS client_slug,
  '100-digital'                         AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_413490347` t
UNION ALL
SELECT
  'ga4'                                 AS platform,
  '413491455'                              AS property_id,
  'STT GDC Web Philippines'                       AS account_name,
  'stt-gdc-web-philippines'                         AS client_slug,
  '100-digital'                         AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_413491455` t
UNION ALL
SELECT
  'ga4'                                 AS platform,
  '413495845'                              AS property_id,
  'STT GDC Web Thailand'                       AS account_name,
  'stt-gdc-web-thailand'                         AS client_slug,
  '100-digital'                         AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_413495845` t
UNION ALL
SELECT
  'ga4'                                 AS platform,
  '434829327'                              AS property_id,
  'STT GDC Web Japan'                       AS account_name,
  'stt-gdc-web-japan'                         AS client_slug,
  '100-digital'                         AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_434829327` t
UNION ALL
SELECT
  'ga4'                                 AS platform,
  '434839993'                              AS property_id,
  'STT GDC Web Global'                       AS account_name,
  'stt-gdc-web-global'                         AS client_slug,
  '100-digital'                         AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_434839993` t
UNION ALL
SELECT
  'ga4'                                 AS platform,
  '434852571'                              AS property_id,
  'STT GDC Web Vietnam'                       AS account_name,
  'stt-gdc-web-vietnam'                         AS client_slug,
  '100-digital'                         AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_434852571` t
UNION ALL
SELECT
  'ga4'                                 AS platform,
  '434854278'                              AS property_id,
  'STT GDC Web Korea'                       AS account_name,
  'stt-gdc-web-korea'                         AS client_slug,
  '100-digital'                         AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_434854278` t
UNION ALL
SELECT
  'ga4'                                 AS platform,
  '434905821'                              AS property_id,
  'STT GDC Web Malaysia'                       AS account_name,
  'stt-gdc-web-malaysia'                         AS client_slug,
  '100-digital'                         AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_434905821` t
UNION ALL
SELECT
  'ga4'                                 AS platform,
  '516276493'                              AS property_id,
  'Reset Data'                       AS account_name,
  'reset-data'                         AS client_slug,
  '100-digital'                         AS agency_slug,
  t._DATA_DATE                          AS metric_date,
  COALESCE(NULLIF(t.sessionSource, ''), '(not set)')               AS session_source,
  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')               AS session_medium,
  COALESCE(NULLIF(t.sessionSourceMedium, ''),
           CONCAT(COALESCE(NULLIF(t.sessionSource, ''), '(not set)'), ' / ',
                  COALESCE(NULLIF(t.sessionMedium, ''), '(not set)')))   AS session_source_medium,
  COALESCE(NULLIF(t.sessionCampaignName, ''), '(not set)')         AS session_campaign_name,
  COALESCE(NULLIF(t.sessionDefaultChannelGroup, ''), '(not set)')  AS session_default_channel_group,
  t.sessions                            AS sessions,
  t.engagedSessions                     AS engaged_sessions,
  CAST(NULL AS INT64)                   AS total_users,
  CAST(NULL AS INT64)                   AS new_users,
  CAST(NULL AS INT64)                   AS screen_page_views,
  CAST(NULL AS NUMERIC)                 AS user_engagement_duration,
  t.eventCount                          AS event_count,
  CAST(t.keyEvents AS NUMERIC)          AS conversions,
  CAST(t.totalRevenue AS NUMERIC)       AS total_revenue,
  CAST(NULL AS NUMERIC)                 AS purchase_revenue,
  CAST(NULL AS INT64)                   AS ecommerce_purchases,
  CAST(NULL AS INT64)                   AS transactions,
  CURRENT_TIMESTAMP()                   AS ingested_at,
  'dts.ga4'                             AS source,
  TO_JSON(t)                            AS raw_row
FROM `bidbrain-analytics.raw_ga4.ga4_TrafficAcquisition_516276493` t;
