steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - australia-southeast1-docker.pkg.dev/$PROJECT_ID/bidbrain/vmch-export:$COMMIT_SHA
      - .
images:
  - australia-southeast1-docker.pkg.dev/$PROJECT_ID/bidbrain/vmch-export:$COMMIT_SHA